version: "3.0"
services:
  kafka:
    image: spotify/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      AUTO_CREATE_TOPICS: 'true'
      ADVERTISED_HOST: '192.168.50.100'
      ADVERTISED_PORT: 9092
      NUM_PARTITIONS: 10
  processor:
    image: dtodt/calc-prc:latest
    container_name: prc
    hostname: prc
    environment:
      BROKER_ADDRESS: '192.168.50.100:9092'
    links:
      - kafka
    depends_on:
      - kafka
  webservice:
    image: dtodt/calc-ws:latest
    container_name: ws
    hostname: ws
    ports:
      - 8000:8000
    environment:
      BROKER_ADDRESS: '192.168.50.100:9092'
      IP: webservice
      PORT: 8000
    links:
      - kafka
    depends_on:
      - kafka
